correctie url in openapi specs
BRP-API/Haal-Centraal-BRP-bewoning pull request #144
Opened 2023-06-16 13:38 UTC by fsamwel

er werd nog verwezen naar de VNG GitHub

2023-06-19 07:31 UTC, CathyDingemanse approved these changes

2023-06-21 07:13 UTC, MelvLee approved these changes

2023-06-23 13:41 UTC, remkomuis approved these changes

2023-06-26 07:03 UTC, MelvLee commented on specificatie/openapi.yaml
> +  description: Haal Centraal BRP bewoning website
externaldocs moet zijn externalDocs

2023-06-26 07:04 UTC, MelvLee requested changes
er moet noh een kleine aanpassing worden gedaan

2023-06-26 08:37 UTC, fsamwel commented on specificatie/openapi.yaml
> +  description: Haal Centraal BRP bewoning website
@MelvLee ik heb het aangepast

2023-06-26 09:30 UTC, merged