wijzigen feature over vastgesteld verblijft niet langer op adres
BRP-API/Haal-Centraal-BRP-bewoning pull request #171
Opened 2023-08-08 13:24 UTC by fsamwel

feature over vastgesteld verblijft niet langer op adres aangepast. de huidige versie ging er vanuit dat dit betekent dat de persoon er nooit gewoond heeft. 

Volgens mij betekent dit (in onderzoek=089999) dat de persoon er nu niet meer woont.
Dit vertaal ik naar:
- vanaf ingangsdatum van het onderzoek woont de persoon zeker niet meer op het adres
- voor de ingangsdatum van het onderzoek woonde de persoon er misschien nog wel

2023-08-08 14:21 UTC, MelvLee commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +Rule: een persoon met aanduiding in onderzoek waarde '089999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek
De proxy kan dit niet bepalen omdat de ingangsdatum van het onderzoek niet wordt teruggegeven door de bewoning api. Zie de OAS

2023-08-09 08:26 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +Rule: een persoon met aanduiding in onderzoek waarde '089999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek
dan moet dat. alternatief is dat de persoon altijd, ook na bepalen van vastgesteld geen bewoner, mogelijke bewoner is

2023-08-09 09:22 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +Rule: een persoon met aanduiding in onderzoek waarde '089999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek
pull request #172 gemaakt voor aanpassing specificaties. die heeft haast, omdat dit ook in het LO moet worden toegevoegd

2023-08-09 10:05 UTC, MelvLee commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +Rule: een persoon met aanduiding in onderzoek waarde '089999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek
Wat mij betreft is het prima om datum ingang onderzoek op te nemen in de OAS van de bewoning api, maar ik denk dat niet alle scenarios met de OAS en rule toevoeging is gedekt.
Hoe moet bewoning bijv. eruit zien in het volgend geval?

```
    Gegeven adres 'A1' heeft de volgende gegevens
    | gemeentecode (92.10) | identificatiecode verblijfplaats (11.80) |
    | 0800                 | 0800010000000001                         |
    Gegeven adres 'A2' heeft de volgende gegevens
    | gemeentecode (92.10) | identificatiecode verblijfplaats (11.80) |
    | 0800                 | 0800010000000002                         |
    En de persoon met burgerservicenummer '000000024' is ingeschreven op adres 'A1' met de volgende gegevens
    | aanduiding in onderzoek (83.10) | datum ingang onderzoek (83.20) | datum aanvang adreshouding (10.30) |
    | 089999                          | 20220526                       | 20200818                           |
    En de persoon is vervolgens ingeschreven op adres 'A2' met de volgende gegevens
    | datum aanvang adreshouding (10.30) |
    | 20220501                           |
```

2023-08-09 10:05 UTC, MelvLee approved these changes

2023-08-09 10:16 UTC, MelvLee commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +Rule: een persoon met aanduiding in onderzoek waarde '089999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek
en ik vraag mij af of er verschil is tussen 089999 met alleen datum ingang onderzoek en 089999 met zowel datum ingang en datum einde onderzoek. Of krijgt je eerst verblijfplaats in onderzoek (bijv. 080000) en als is vastgesteld dat de persoon niet meer op het adres verblijft dat je dan pas 089999 krijgt

2023-08-10 12:47 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +Rule: een persoon met aanduiding in onderzoek waarde '089999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek
@MelvLee ik heb enkele scenario's toegevoegd die gaan over 089999 op een historische verblijfplaats, ook met volgende verblijfplaats met gedeeltelijk onbekende datum aanvang, en met beëindigd onderzoek 089999

2023-08-29 13:51 UTC, remkomuis commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +    | 2022-09-12 | 2022-09-12 tot 2022-09-13 | peildatum valt na datum aanvang volgende verblijfplaats                                                             |
De rule is dat een beëindigd onderzoek met waarde 089999 "niet" wordt "gebruikt", maar de scenario's geven aan dat iemand zowel voor als na het onderzoek wordt beschouwd als mogelijke bewoner, en zelfs na verhuizing nog. 
1. Klopt dat wel met de tekst in de rule?
2. Waarom is dit een mogelijke bewoner, ook nadat hij zich op een nieuw adres heeft ingeschreven na beëindiging van het onderzoek?

2024-02-01 16:56 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/vastgesteld-verblijft-niet-op-adres.feature
> +    | 2022-09-12 | 2022-09-12 tot 2022-09-13 | peildatum valt na datum aanvang volgende verblijfplaats                                                             |
inderdaad. niet gebruikt betekent dat we doen alsof het er nooit geweest is. Scenario's aangepast.

2024-02-01 16:58 UTC, fsamwel commented
pull request is aangepast:
- feature aangepast zodat deze aansluiten op de rules
- feature gemaakt voor periode, 
- de feature(s) verplaatst naar gba
- feature met testscenario's toegevoegd (tot nu alleen voor bewoning met periode)

2024-02-02 15:25 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-07-12 | 2022-07-12 tot 2022-07-13 | peildatum valt na de dag ingang onderzoek en voor datum einde onderzoek en voor datum aanvang volgende verblijfplaats |
Ik dacht dat persoon er niet woont vanaf de ingangsdatum onderzoek als is vastgesteld dat persoon er niet woont.

2024-02-02 15:25 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-08-12 | 2022-08-12 tot 2022-08-13 | peildatum valt na de dag ingang onderzoek en na datum einde onderzoek                                                 |
idem. Dit staat niet met zoveel woorden in de HUP maar heb ik ergens gehoord (LAA dag?). Maar even aan Frans vragen maandag.

2024-02-02 15:25 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-07-12 | 2022-07-12 tot 2022-07-13 | peildatum valt na de dag ingang onderzoek en voor datum einde onderzoek en voor datum aanvang volgende verblijfplaats |
zie boven

2024-02-02 15:25 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-08-12 | 2022-08-12 tot 2022-08-13 | peildatum valt na de dag ingang onderzoek en na datum einde onderzoek en voor datum aanvang volgende verblijfplaats   |
zie boven.

2024-02-08 16:13 UTC, CathyDingemanse reviewed
scenario regel 89 moet nog worden aangepast toch? Voor de ingangsdatum onderzoek is persoon bewoner en geen mogelijke bewoner. We gaan nog navragen of we in onderzoek moeten leveren voor de bewoner.

2024-02-08 16:39 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-01-01 | 2022-01-01 tot 2022-01-02 | peildatum voor datum ingang van het onderzoek |
voor de datum ingang onderzoek is persoon bewoner.

2024-02-08 16:39 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-01-01 | 2022-01-01 tot 2022-01-02 | peildatum voor ingang onderzoek             |
Persoon is hier bewoner. Eigenlijk gaat dit scenario over andere businesslogic als hier beschreven. Ik zou niet 2 rules "mengen" in 1 scenario, want dan blijven we aanpassen als er eentje wijzigt.

2024-02-08 16:40 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +  Rule: een persoon met aanduiding in onderzoek waarde '089999' of '589999' wordt geleverd als mogelijke bewoner tot de ingangsdatum van het onderzoek
Is niet outdated...

2024-02-12 07:29 UTC, KayodeBakker requested changes
Ik heb een hoop gevonden in de scenario's dat voor mij raar is. Kijkende naar de hoeveelheid houdt dit vaak in dat ik iets compleet verkeerd zie, maar ben benieuwd.

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
Waarom verwachten we hier een mogelijke bewoner? Geen 1 van de voorbeelden datum tot overlapt met de datum aanvang adreshouding van A2. Er zijn niet eens onvolledige datums ter sprake.

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
Ook hier snap ik niet waarom we mogelijke bewoner hebben staan.

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-met-periode/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
Waarom hebben we hier mogelijke bewoner staan?

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-met-periode/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
Waarom hebben we hier mogelijke bewoner staan?

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +    Scenario: persoon verblijft mogelijk nog op het gevraagde adres en <scenario>
Zie 'features\raadpleeg-bewoning-op-peildatum\gba\in-onderzoek-gba.feature:118' van abstract scenario ' Abstract Scenario: 'hele categorie verblijfplaats' is in onderzoek en '.

Met andere woorden we vergeten hier inOnderzoek mee te leveren in de scenario en mijn resultaat is wel correct. Dit zie ik ook verkeerd gaan bij volgende scenarios in de gehele feature.

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 20220801               | 2022-08-12 | 2022-08-12 tot 2022-08-13 | na beëindigen van het onderzoek          | peildatum valt na de dag ingang onderzoek en na datum einde onderzoek en voor datu
Hier zou geen bewoning uit moeten komen. De volgende datum is 2022-08-01 en de peildatum is 2022-08-12. Je zal dus nooit op de gegeven AO identificatie een bewoning vinden want deze is al lang afgerond.

2024-02-12 07:29 UTC, KayodeBakker commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 20220810               | 2022-08-12 | 2022-08-12 tot 2022-08-13 | vanaf datum beëindigen van het onderzoek | peildatum valt na de dag ingang onderzoek en na datum einde onderzoek en voor datu
Hier hetzelfde als bij de vorige scenario regel.

2024-02-12 16:24 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +  Rule: een persoon met aanduiding in onderzoek waarde '089999' of '589999' wordt geleverd als mogelijke bewoner tot de ingangsdatum van het onderzoek
> Is niet outdated...

dit is aangepast. De persoon wordt geleverd als bewoner:
`Rule: een persoon met aanduiding in onderzoek waarde '089999' of '589999' wordt geleverd als bewoner tot de ingangsdatum van het onderzoek`

2024-02-12 16:47 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-01-01 | 2022-01-01 tot 2022-01-02 | peildatum voor datum ingang van het onderzoek |
goed punt. ik heb de rule aangepast

2024-02-12 16:50 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-01-01 | 2022-01-01 tot 2022-01-02 | peildatum voor ingang onderzoek             |
deze opmerking begrijp ik niet. welke andere businesslogica?

2024-02-12 16:52 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | adresseerbaarObjectIdentificatie | 0800010000000001 |
hier moet inderdaad wel onderzoek meegeleverd worden door de gba API. is aangepast

2024-02-12 16:56 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-01-01 | 2023-01-01 | 2022-01-01 tot 2022-05-26 | periode loopt tot na de datum ingang onderzoek      |
zie de voorgaande rule: 
```Rule: een persoon met aanduiding in onderzoek waarde '089999' of '589999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek```

2024-02-12 16:57 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 2022-01-01 | 2023-01-01 | 2022-01-01 tot 2022-05-26 | periode loopt tot na de datum ingang onderzoek      |
zie de rule: ```Rule: een persoon met aanduiding in onderzoek waarde '089999' of '589999' wordt niet geleverd als bewoner vanaf de ingangsdatum van het onderzoek```

2024-02-12 16:59 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
zie de rule

2024-02-12 16:59 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +    Scenario: persoon verblijft mogelijk nog op het gevraagde adres en <scenario>
klopt, is inmiddels toegevoegd

2024-02-12 17:07 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 20220801               | 2022-08-12 | 2022-08-12 tot 2022-08-13 | na beëindigen van het onderzoek          | peildatum valt na de dag ingang onderzoek en na datum einde onderzoek en voor datu
ja klopt, scenario is aangepast

2024-02-12 17:07 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      | 20220810               | 2022-08-12 | 2022-08-12 tot 2022-08-13 | vanaf datum beëindigen van het onderzoek | peildatum valt na de dag ingang onderzoek en na datum einde onderzoek en voor datu
ook aangepast

2024-02-12 17:09 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
zie de rule

2024-02-12 17:09 UTC, fsamwel commented on features/raadpleeg-bewoning-op-peildatum/gba/vastgesteld-verblijft-niet-op-adres-gba.feature
> +      En heeft de bewoning een mogelijke bewoner met de volgende gegevens
zie de rule

2024-02-15 08:28 UTC, merged