scenario's overlijden voor geleverde periode
BRP-API/Haal-Centraal-BRP-bewoning pull request #210
Opened 2023-10-19 16:23 UTC by fsamwel

scenario's die tonen welke periode van bewoning geleverd moet worden bij opschorting bijhouding.

@KayodeBakker deze scenario's falen op v2.0.14 en v2.0.15 (concept versie)

2023-10-20 11:52 UTC, KayodeBakker commented
@fsamwel Ik snap de wijziging niet.
Bijv. Abstract Scenario: persoon is overleden tijdens verblijf op gevraagde adres en gevraagd wordt <scenario>.
Persoon woonde ooit op 0800010000000002 van 2021-03-14 tot 2021-05-26 waar de persoon op A1 woont (0800010000000001). Waarom verwachten we dan een periode van 2021-05-26 naar 2011-11-01 als die periode om 0800010000000001 gaat en niet 0800010000000002?

2023-10-23 07:15 UTC, KayodeBakker requested changes

2023-10-23 07:15 UTC, KayodeBakker commented on features/raadpleeg-bewoning-met-periode/gba/opschorting-bijhouding-gba.feature
> +  Abstract Scenario: persoon is overleden tijdens verblijf op gevraagde adres en gevraagd wordt <scenario>
@fsamwel  Ik snap de wijziging niet.
Bijv. Abstract Scenario: persoon is overleden tijdens verblijf op gevraagde adres en gevraagd wordt .
Persoon woonde ooit op 0800010000000002 van 2021-03-14 tot 2021-05-26 waar de persoon op A1 woont (0800010000000001). Waarom verwachten we dan een periode van 2021-05-26 naar 2011-11-01 als die periode om 0800010000000001 gaat en niet 0800010000000002?

Heb je hier toevallig een identificatie copy pasta fout gemaakt of begrijp ik iets totaal niet?

2023-10-23 07:27 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/opschorting-bijhouding-gba.feature
> +  Abstract Scenario: persoon is overleden tijdens verblijf op gevraagde adres en gevraagd wordt <scenario>
moet natuurlijk 0800010000000001 1. Was kopieerfout. Aangepast

2023-10-23 07:41 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/opschorting-bijhouding-gba.feature
> +  Abstract Scenario: persoon is overleden tijdens verblijf op gevraagde adres en gevraagd wordt <scenario>
@KayodeBakker scenario faalt onder v2.0.15 trouwens ook na de correctie. deze geeft als begindatum van bewoning 2021-01-01, maar persoon woont er pas sinds 2021-05-26.

2023-10-23 15:28 UTC, MelvLee approved these changes

2023-10-24 09:33 UTC, merged