Rule en voorbeelden voor leveren bewoning met bewoners voor de periode na de onzekerheidsperiode
BRP-API/Haal-Centraal-BRP-bewoning pull request #211
Opened 2023-10-19 17:16 UTC by fsamwel

Dit is een eerste stuk, voorbeelden voor onbekende aanvang volgende verblijfplaats moeten nog volgen

@KayodeBakker versies v2.0.14 en v2.0.15 (concept versie) leveren nu alleen de bewoning met mogelijke bewoners, niet de bewoning met bewoners

2023-10-20 08:29 UTC, CathyDingemanse reviewed
Er zijn toch al scenario's met de combinatie van bewoners en mogelijke bewoners?

2023-10-20 09:59 UTC, CathyDingemanse reviewed
verder helemaal goed.
Ik overleg graag even met @MelvLee waar we deze features kunnen onderbrengen. De mappen zijn niet gelijk voor periode en peildatum.

2023-10-20 10:47 UTC, KayodeBakker requested changes

2023-10-20 10:47 UTC, KayodeBakker commented on features/raadpleeg-bewoning-met-periode/gba/mogelijke-bewoner-gba.feature
> +    | 20210000      | 2021-01-01 tot 2022-01-01 | 2022-01-01 tot 2022-01-01 |
@fsamwel Excuseer een mogelijke verwarring aan mijn kant, maar de datumTot is 2022-01-01. Waarom hanteer ik dan nog een periode bewoner van 2022-01-01 tot 2022-01-01? Ik dacht dat deze situatie alleen kon ontstaan als de datumTot 2022-01-02 was en dat we dan een bewoner periode krijgen van 2022-01-01 tot 2022-01-02.

Ik dacht dat er een afspraak was gemaakt dat de gegeven datumTot nooit een periodeVan kan zijn of heb ik dit verkeerd?

2023-10-23 07:30 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/mogelijke-bewoner-gba.feature
> +    | adresseerbaarObjectIdentificatie | 0800010000000002  |
aangepast

2023-10-23 07:33 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/mogelijke-bewoner-gba.feature
> +    | 20210000      | 2021-01-01 tot 2022-01-01 | 2022-01-01 tot 2022-01-01 |
klopt. zat fout in scenario. is nu aangepast

2023-10-23 07:35 UTC, fsamwel commented on features/raadpleeg-bewoning-met-periode/gba/mogelijke-bewoner-gba.feature
> +    | 20210000      | 2021-01-01 tot 2022-01-01 | 2022-01-01 tot 2022-01-01 |
scenario slaagt nu wel op de nieuwste 2.0.15

2023-10-23 11:11 UTC, merged