scenario combinatie vorige, onbekende gevraagde en onbekende volgende met overlap
BRP-API/Haal-Centraal-BRP-bewoning pull request #217
Opened 2023-10-24 09:12 UTC by fsamwel

@KayodeBakker v2.0.15 geeft in dit scenario helemaal geen bewoning/bewoner, terwijl wel een mogelijke bewoner werd verwacht

2023-10-24 09:33 UTC, MelvLee approved these changes

2023-10-24 11:49 UTC, KayodeBakker requested changes

2023-10-24 11:49 UTC, KayodeBakker commented on features/raadpleeg-bewoning-met-periode/gba/mogelijke-bewoner-gba.feature
> +  Scenario: persoon heeft onbekende aanvang adreshouding en deels/geheel overlappende onbekende aanvang volgende adreshouding en vorige adreshouding in de onzekerheidsperiode van aanvang adreshouding
Hoe kan het dat dit onder de rule 'Rule: een persoon met bekende aanvang vorige adreshouding die in de onzekerheidsperiode van de onbekende aanvang adreshouding ligt, is een mogelijke bewoner voor het deel van de periode in de onzekerheidsperiode dat na de datum aanvang vorige adreshouding ligt' valt?

De titel van deze scenario geeft aan dat we een volgende adreshouding datum hebben dat overlapt met de aanvang adreshouding. De rule noemt alleen adres aanvang datum en de vorige. Uit eerdere gespreken (ook als voorstel van Melvin) dien ik in dit geval de volgende datum te beschouwen als NULL of heeft geen overlap.

Kan je deze toelichten @fsamwel ?

2023-10-26 07:49 UTC, MelvLee commented
zelfde incorrecte scenario in p.r. #216 zit nu op regel 953

2023-10-26 14:50 UTC, merged