bewoning in periode specificaties
BRP-API/Haal-Centraal-BRP-bewoning pull request #220
Opened 2023-10-25 09:56 UTC by MelvLee

Een rewrite van de overzicht-gba feature file waarbij de scenarios zijn beschreven vanuit gebruikersperspectief. Naar mijn mening zou een consumer in essentie de bewoning in een periode operatie gebruiken (en niet bewoning op peildatum) om te bepalen of de samenstelling van bewoners in de gevraagde periode wijzigt. De scenarios zijn daarom zodanig beschreven zodat dit wordt gevalideerd.

Omdat er bij deel/geheel onbekende datum aanvang ook moet worden gekeken naar de vorige en volgende datum aanvang adreshouding zijn er voor elke scenario vier varianten gemaakt (geen vorig\geen volgend, geen vorig\wel volgend, wel vorig\geen volgend en wel vorig\wel volgend)

Ook is geprobeerd de rules generieker/globaler te beschrijven, zodat volgende rules op vorige rules voortborduren. Dit om redundante herhalingen en vooral rules die elkaar tegenspreken te voorkomen.

Met v2.0.16 falen nog 2 scenarios in de overzicht-gba.feature:
- [ ] 500 melding bij datum aanvang adreshouding is 20101200. Dit wordt omgezet naar datum 2010-13-01 (regel 336)
- [ ] geen bewoning als geheel/deels onbekende aanvang adreshouding de vorige datum aanvang adreshouding overlappen. (regel 1119 en 1121). Ik moet nog bekijken of deze hetzelfde zijn als de scenarios in p.r. #217, #216, #214, #212

Mogelijk mis ik nog scenarios maar die kunnen tzt worden toegevoegd

2023-10-25 19:35 UTC, KayodeBakker requested changes
Alles draait groen, los van de zaken uit pr #212, als mijn opmerking als correct wordt gezien.

2023-10-25 19:35 UTC, KayodeBakker commented on features/raadpleeg-bewoning-met-periode/gba/overzicht-gba.feature
> +  Abstract Scenario: De gevraagde periode overlapt de geheel overlappende onzekerheidsperiodes van de geheel/deels onbekende datum aanvang adreshouding én geheel/deels onbekende datum aanvang volgend
Ik vermoed dat deze scenario niet correct is.
Alle 3 de voorbeelden hebben dezelfde verwachting, maar volgens mij is dat niet correct om de volgende redenen:

Casus | 00000000 | 00000000 |:
Als je een vorige datum hebt met waarde 2009-05-10 en de volgende twee adressen zijn 0000-00-00 dan is het logisch dat de verwachting 2009-05-11 tot 2011-01-01 is voor de mogelijke bewoners. Namelijk 1 dag na begin van vorige en de datum tot.

De verwachting voor deze is correct.

Casus | 20090000 | 20090000 |
vorige: 2009-05-10
huidige: 2009-00-00 (onzekerheidsperiode 2009-05-11 - 2010-01-01)
volgende: 2009-00-00 (onzekerheidsperiode 2009-05-11 - 2010-01-01)

datum van: 2008-01-01
datum tot: 2011-01-01

periods:
2008-01-01 - 2009-05-10 (niks)
2009-05-10 - 2009-05-11 (niks)
2009-05-11 - 2010-01-01 (mogelijke bewoners)
2010-01-01 - 2011-01-01 (niks)

Het is niet logisch om te zeggen dat een mogelijke bewoner bent tot 2011-01-01 als de onzekerheidsperiode van een 2009 datum alleen maar 2009-01-01 tot 2010-01-01 is.

De juiste verwachting hoort te zijn dat je alleen een mogelijke bewoner krijgt voor de periode 2009-01-01 tot 2010-01-01.

Casus | 20090500 | 20090500 |
Vergelijkbaar als de vorige.

vorige: 2009-05-10
huidige: 2009-05-00 (onzekerheidsperiode 2009-05-11 - 2009-06-01)
volgende: 2009-05-00 (onzekerheidsperiode 2009-05-11 - 2009-06-01)

datum van: 2008-01-01
datum tot: 2011-01-01

periods:
2008-01-01 - 2009-05-10 (niks)
2009-05-10 - 2009-05-11 (niks)
2009-05-11 - 2009-06-01 (mogelijke bewoners)
2009-06-01 - 2011-01-01 (niks)

Ook hier is het niet correct om te zeggen dat de periode 2009-05-11 tot 2011-01-01 is voor mogelijke bewoner want de onzekerheidsperiode eindigt op 2009-06-01 en zal de volgende adreshouding sowieso van stand zijn.
De correcte periode zou zijn: 2009-05-11 - 2009-06-01

Als gevolg hiervan zou mijn voorstel zijn om ieder een eigen scenario te geven of een unieke verwachting binnen het voorbeeld.

2023-10-26 06:25 UTC, MelvLee commented on features/raadpleeg-bewoning-met-periode/gba/overzicht-gba.feature
> +  Abstract Scenario: De gevraagde periode overlapt de geheel overlappende onzekerheidsperiodes van de geheel/deels onbekende datum aanvang adreshouding én geheel/deels onbekende datum aanvang volgend
klopt. Ik heb de scenarios aangepast

2023-10-26 07:00 UTC, KayodeBakker approved these changes

2023-11-01 12:55 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-met-periode/gba/overzicht-gba.feature
> +
ik heb een poging gedaan, maar hoe jij het hier zegt is toch beter :-).

2023-11-01 12:56 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-met-periode/gba/overzicht-gba.feature
> +
ik ben nog niet klaar...

2023-11-01 14:11 UTC, CathyDingemanse reviewed
nu wel klaar. Tjonge wat een klus. Super!

2023-11-01 14:11 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-met-periode/gba/overzicht-gba.feature
> +  Scenario: De gevraagde periode overlapt de deels overlappende onzekerheidsperiodes van de deels onbekende datum aanvang adreshouding en deels onbekende datum aanvang volgende adreshouding en de dat
holymoly. Ik zou ook niet weten hoe dit duidelijker te formuleren. Zo complex is het ook gewoon. En het klopt.

2023-11-01 14:11 UTC, CathyDingemanse commented on features/raadpleeg-bewoning-met-periode/gba/overzicht-gba.feature
> +  # res       |~~--|
todo?

2023-11-03 08:09 UTC, merged