fix: personen met briefadres bij raadpleeg bewoning scenarios
BRP-API/Haal-Centraal-BRP-bewoning pull request #224
Opened 2024-01-31 11:53 UTC by MelvLee

- [x] raadpleeg bewoning op peildatum scenarios toevoegen
- [ ] raadpleeg bewoning op peildatum in onderzoek scenarios aanpassen
- [ ] raadpleeg bewoning met periode scenarios toevoegen
- [ ] raadpleeg bewoning met periode in onderzoek scenarios aanpassen
- [ ] automation voor briefadres stapdefinitie

2024-01-31 14:33 UTC, CathyDingemanse approved these changes

2024-02-01 11:44 UTC, fsamwel commented on features/step_definitions/stepdefs.js
> +            [ 'adres_functie', 'B']
ik zie hier wel een aanpassing van het script voor de nieuwe stap, met toevoegen van adres_functie. Maar ik zie nog geen aanpassing waar bij de normale stap (de persoon is ingeschreven op adres '(.*)' met de volgende gegevens) adres_functie 'W' wordt toegevoegd. Zie ik iets over het hoofd of moet dat nog?

2024-02-01 12:21 UTC, MelvLee commented on features/step_definitions/stepdefs.js
> +            [ 'adres_functie', 'B']
Dat is al aangepast in een ander commit dat niet in deze p.r. zit. Ik wou namelijk zeker van zijn dat het toevoegen van 'W' als adres_functie in de huidige scenarios niet tot ander gedrag leidt van de huidige bewoning api. Zie hiervoor commit: https://github.com/BRP-API/Haal-Centraal-BRP-bewoning/commit/73868b6d643bfb8f280205be2f31058e7cf6fcfe

2024-02-02 12:35 UTC, fsamwel commented
@MelvLee is er ook een stap voor "de persoon is vervolgens ingeschreven op adres 'A2' met de volgende gegevens" voor briefadres? Ik zou namelijk aan de testfeatures hier wel een paar extra voorbeelden voor toevoegen. O.a. om te testen dat afsnijden van onbekende datum aanvang ook werkt als vorige is een briefadres. En om te testen dat  einddatum (bekend of onbekend) ook correct wordt gebruikt bij volgende verblijf is briefadres.

Wordt dat zoiets? "de persoon heeft vervolgens adres '(.*)' als briefadres opgegeven met de volgende gegevens"?

2024-02-05 05:09 UTC, KayodeBakker approved these changes

2024-02-05 05:19 UTC, KayodeBakker requested changes
Bij de abstract scenario features\raadpleeg-bewoning-op-peildatum\gba\test\echte-datums-gba.feature op regel 323 worden geen bewoningen gevonden dankzij de wijziging van deze PR. Bijv. bij 'datum aanvang is gecorrigeerd naar eerdere datum en peildatum is nieuwe datum aanvang' wordt de volgende SQL insert gegenereerd voor verblijfplaatsen.

```sql
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '1291', '4', 'W', '0800', '20210516' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum,onjuist_ind) VALUES('7333', '1292', '3', 'W', '0800', '20210526', 'O' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,volg_nr,adres_id,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '2', '1292', '0800', '20210520' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '1293', '1', 'W', '0800', '20210730' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '1294', '0', 'W', '0800', '20211014' );
```

Hier zouden 4 verblijfplaatsen zijn waaronder 1 dat wordt gecorrigeerd met de volgende regel: 'En de 'verblijfplaats' is gecorrigeerd naar de volgende gegevens' maar de insert behorende aan deze correctie bevat geen functie adres. De besproken regel rondom filtering voor functie adres is dat bewoningen zonder functie adres of waar de functie adres een 'B' bevat weg worden gefilterd.

Dankzij deze insert wordt 1 bewoning weg gefilterd en dat is nou net de gene waar om wordt gevraagd. Graag aan de stepdefs toevoegen dat bij een correctie ook een functie adres wordt meegegeven.

Dit probleem komt ook voor bij 'features\raadpleeg-bewoning-op-peildatum\gba\test\onbekend-datums-gba.feature'.

2024-02-05 07:49 UTC, MelvLee reviewed
> @MelvLee is er ook een stap voor "de persoon is vervolgens ingeschreven op adres 'A2' met de volgende gegevens" voor briefadres? Ik zou namelijk aan de testfeatures hier wel een paar extra voorbeelden voor toevoegen. O.a. om te testen dat afsnijden van onbekende datum aanvang ook werkt als vorige is een briefadres. En om te testen dat  einddatum (bekend of onbekend) ook correct wordt gebruikt bij volgende verblijf is briefadres.

Wordt dat zoiets? "de persoon heeft vervolgens adres '(.*)' als briefadres opgegeven met de volgende gegevens"? 

De stap definitie is toegevoegd

2024-02-05 07:54 UTC, MelvLee reviewed
> Bij de abstract scenario features\raadpleeg-bewoning-op-peildatum\gba\test\echte-datums-gba.feature op regel 323 worden geen bewoningen gevonden dankzij de wijziging van deze PR. Bijv. bij 'datum aanvang is gecorrigeerd naar eerdere datum en peildatum is nieuwe datum aanvang' wordt de volgende SQL insert gegenereerd voor verblijfplaatsen.

```sql
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '1291', '4', 'W', '0800', '20210516' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum,onjuist_ind) VALUES('7333', '1292', '3', 'W', '0800', '20210526', 'O' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,volg_nr,adres_id,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '2', '1292', '0800', '20210520' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '1293', '1', 'W', '0800', '20210730' );
INSERT INTO public.lo3_pl_verblijfplaats(pl_id,adres_id,volg_nr,adres_functie,inschrijving_gemeente_code,adreshouding_start_datum) VALUES('7333', '1294', '0', 'W', '0800', '20211014' );
```

Hier zouden 4 verblijfplaatsen zijn waaronder 1 dat wordt gecorrigeerd met de volgende regel: 'En de 'verblijfplaats' is gecorrigeerd naar de volgende gegevens' maar de insert behorende aan deze correctie bevat geen functie adres. De besproken regel rondom filtering voor functie adres is dat bewoningen zonder functie adres of waar de functie adres een 'B' bevat weg worden gefilterd.

Dankzij deze insert wordt 1 bewoning weg gefilterd en dat is nou net de gene waar om wordt gevraagd. Graag aan de stepdefs toevoegen dat bij een correctie ook een functie adres wordt meegegeven. 

Ik heb de scenario aangepast door functie adres handmatig op te geven. De bedoeling van die stap definitie is juist dat zelf kan worden bepaald hoe (in dit geval) de nieuwe verblijfplaats na correctie eruit moet zien. Bijv. dat woonadres gecorrigeerd moet worden naar briefadres. En dat zou niet goed gaan als automatisch functie adres wordt gezet

2024-02-12 12:28 UTC, merged